apiVersion: v1
kind: Service
metadata:
  name: app-tc-backend-s3-svc
  namespace: fiap 
spec:
  selector:
    app: app-tc-backend-s3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
