name: EKS-Deploy
on:
    workflow_dispatch:  # Configuração para deploy manual
env:
    CLUSTER_NAME: eks-fiap-cluster
          
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    
    environment:
      name: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get Session Token
        run: echo aws sts get-session-token 
  
      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Deploy EKS
        run: |
            kubectl apply -f src/k8s/1-namespace.yaml
            kubectl apply -f src/k8s/2-secrets.yaml
            kubectl apply -f src/k8s/3-deployment.yaml
            kubectl apply -f src/k8s/4-hpa.yaml
            kubectl apply -f src/k8s/5-services.yaml